Adding the function `parseOrNull()`
swiftzer/semver pull request #13
Opened 2023-04-11 14:08 UTC by mfederczuk

It's easier to work with `parseOrNull()` if the intent is to not crash/throw an exception in the case of an invalid version string.

Before:

```kotlin
try {
    val semVer: SemVer = SemVer.parse(version)

    // ...
} catch (_: IllegalArgumentException) {
    // ...
}
```

After, with `parseOrNull()`:

```kotlin
val semVer: SemVer? = Semver.parseOrNull(version)

if (semVer != null) {
    // ...
} else {
    // ...
}
```

2023-04-12 22:23 UTC, rbbl-dev commented
i'm this should be an additional function instead to not break the existing api and offer more flexibility

2023-05-16 02:44 UTC, ericksli requested changes

2023-05-16 02:44 UTC, ericksli commented on src/test/java/net/swiftzer/semver/SemVerTest.kt
> +    fun parseInvalid2() {
Can you please rename as `parseOrNull`?

2023-05-16 02:44 UTC, ericksli commented on src/test/java/net/swiftzer/semver/SemVerTest.kt
> +    fun parseInvalid1() {
As `parseInvalid2` become `parseOrNull`, then no need to rename this function.

2023-05-17 14:56 UTC, ericksli approved these changes

2023-05-17 14:56 UTC, merged

2023-05-17 14:56 UTC, ericksli commented
Thank you!